import { authenticate } from './flow.mjs'
export async function designFlow(page, info, expect) {
  const errors = []
  page.on('pageerror', (e) => errors.push(e.message))
  await authenticate(page)
  await page.getByRole('button', { name: 'Memory', exact: true }).click()
  const panel = page.getByRole('region', { name: 'Memory and learning', exact: true })
  await expect(panel.getByRole('status')).toHaveCount(0)
  await expect(panel.getByRole('textbox', { name: 'Import facts JSON', exact: true })).toBeHidden()
  await panel.getByRole('button', { name: 'Add explicit fact', exact: true }).click()
  const content = 'Design review fact ' + Date.now()
  await panel.getByRole('textbox', { name: 'Content', exact: true }).fill(content)
  await panel.getByRole('button', { name: 'Save fact', exact: true }).click()
  const row = panel.locator('article').filter({ has: page.getByText(content, { exact: true }) })
  await row.getByRole('button', { name: 'Update', exact: true }).click()
  await row.getByRole('textbox', { name: 'Content', exact: true }).fill(content + ' changed')
  await row.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(row.getByText(content, { exact: true })).toBeVisible()
  await row.getByRole('button', { name: 'Update', exact: true }).click()
  await row.getByRole('textbox', { name: 'Content', exact: true }).fill(content + ' changed')
  await row.getByRole('button', { name: 'Save fact', exact: true }).click()
  await expect(panel.getByText(content + ' changed', { exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath('facts-desktop.png') })
  await panel.getByRole('button', { name: 'Activity', exact: true }).click()
  await expect(
    panel.getByRole('textbox', { name: 'Reviewed live-model evaluation report JSON', exact: true })
  ).toBeHidden()
  await expect(panel.getByRole('heading', { name: 'Learning activity', exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath('activity-desktop.png') })
  await panel.getByText('Advanced controls', { exact: true }).click()
  await expect(
    panel.getByRole('textbox', { name: 'Reviewed live-model evaluation report JSON', exact: true })
  ).toBeVisible()
  await panel.getByText('Advanced controls', { exact: true }).click()
  await page.screenshot({ path: info.outputPath('workspace-desktop.png') })
  await page.getByRole('button', { name: 'Collapse sidebar', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('activity-mobile-before.png') })
  expect(await panel.evaluate((el) => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
  await panel.getByRole('button', { name: 'Saved facts', exact: true }).click()
  await page.screenshot({ path: info.outputPath('facts-mobile-before.png') })
  expect(errors).toEqual([])
  await panel.getByRole('button', { name: 'Add explicit fact', exact: true }).click()
  await expect(panel.getByRole('textbox', { name: 'Content', exact: true })).toBeFocused()
  await page.screenshot({ path: info.outputPath('facts-mobile.png') })
  await panel.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(panel.getByRole('textbox', { name: 'Content', exact: true })).toHaveCount(0)
}

export async function appearanceFlow(page, info, expect) {
  const errors = []
  page.on('pageerror', (e) => errors.push(e.message))
  await authenticate(page)
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: 'General', exact: true }).click()
  await page.getByRole('button', { name: 'Dark', exact: true }).click()
  await page.keyboard.press('Escape')
  try {
    await page.getByRole('button', { name: 'Memory', exact: true }).click()
    const panel = page.getByRole('region', { name: 'Memory and learning', exact: true })
    const facts = panel.getByRole('button', { name: 'Saved facts', exact: true })
    await facts.focus()
    await page.keyboard.press('ArrowRight')
    await expect(panel.getByRole('button', { name: 'Fact review', exact: true })).toBeFocused()
    await page.keyboard.press('Enter')
    await expect(
      panel.getByRole('heading', { name: 'No facts to review', exact: true })
    ).toBeVisible()
    await page.screenshot({ path: info.outputPath('review-empty-dark.png') })
    await panel.getByRole('button', { name: 'Settings', exact: true }).click()
    await expect(panel.getByRole('button', { name: 'Save policy', exact: true })).toBeVisible()
    await page.screenshot({ path: info.outputPath('settings-dark.png') })
    await panel.getByRole('button', { name: 'Saved facts', exact: true }).click()
    await panel.getByRole('button', { name: 'Saved facts', exact: true }).click()
    await expect(
      panel.getByRole('button', { name: 'Add explicit fact', exact: true })
    ).toBeVisible()
    expect(errors).toEqual([])
  } finally {
    await page.getByRole('button', { name: 'Settings', exact: true }).first().click()
    await page.getByRole('button', { name: 'General', exact: true }).click()
    await page.getByRole('button', { name: 'Light', exact: true }).click()
  }
}
